import type { NextPage } from "next";
import dynamic from "next/dynamic";
import Head from "next/head";
import { useRouter } from "next/router";
import React, { useEffect, useState } from "react";
import withAuthentication from "../../../hoc/ProtectedRoute";
import { ActiveWindowContext } from "../../../hooks/ActiveWindowContext";
import { ShowBucketsContext } from "../../../hooks/ShowBucketsContext";
import SideNav from "../../../modules/SideNav/SideNav";

const TokensDashboard = dynamic(
  () => import("../../../modules/Tokens/TokensDashboard"),
  { ssr: false }
);

const Tokens: NextPage = () => {
  const router = useRouter();
  const { token } = router.query;
  const [showBuckets, setShowBuckets] = useState<boolean>(true);
  const [activeWindow, setActiveWindow] = useState("payment");

  useEffect(() => {
    setActiveWindow("payment");
  }, []);

  return (
    <ShowBucketsContext.Provider value={{ showBuckets, setShowBuckets }}>
      <ActiveWindowContext.Provider value={{ activeWindow, setActiveWindow }}>
        <div className=" h-full overflow-hidden  bg-[#141417] text-white antialiased">
          <Head>
            <title>Solinvest | Dashboard</title>
            {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
          </Head>
          <div className="flex ">
            <div className="w-[6%]  border-r border-[#2B2B2E]  ">
              <SideNav />
            </div>
            <div className="w-[96%]  ">
              <TokensDashboard token={token} />
            </div>
          </div>
        </div>{" "}
      </ActiveWindowContext.Provider>
    </ShowBucketsContext.Provider>
  );
};

export default withAuthentication(Tokens);
