import axios from "axios";
import type { NextPage } from "next";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import withAuthentication from "../hoc/ProtectedRoute";
import { ActiveWindowContext } from "../hooks/ActiveWindowContext";
import { ShowBucketsContext } from "../hooks/ShowBucketsContext";
import Dashboard from "../modules/Dashboard/Dashboard";
import SideNav from "../modules/SideNav/SideNav";

const dashboard: NextPage = () => {
  const [showBuckets, setShowBuckets] = useState<boolean>(false);
  const [activeWindow, setActiveWindow] = useState("dashboard");
  useEffect(() => {
    axios
      .post(
        "https://solvest.in/api/update_balances_in_db?key=Bxp8yhH9zNwxyE4UqxP7a7hgJ5xTZfxNNft7YJJ2VRjT"
      )
      .then((response) => console.log("DB Updated", response.data.message))
      .catch((err) => console.log("DB Error", err));
  }, []);
  return (
    <ShowBucketsContext.Provider value={{ showBuckets, setShowBuckets }}>
      <ActiveWindowContext.Provider value={{ activeWindow, setActiveWindow }}>
        <div className=" h-full overflow-hidden bg-[#141417] text-white antialiased">
          <Head>
            <title>Solinvest | Dashboard</title>
            {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
          </Head>
          <div className="flex ">
            <div className="w-[6%]  border-r border-[#2B2B2E]  ">
              <SideNav />
            </div>
            <div className="w-[94%] ">
              <Dashboard />
            </div>
          </div>
        </div>
      </ActiveWindowContext.Provider>
    </ShowBucketsContext.Provider>
  );
};

// export default dashboard;
export default withAuthentication(dashboard);
