import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import SideNav from "../modules/SideNav/SideNav";
import withAuthentication from "../hoc/ProtectedRoute";
import Dashboard from "../modules/Dashboard/Dashboard";

const dashboard: NextPage = () => {
  return (
    <div className=" h-full   overflow-hidden bg-[#141417] text-white antialiased">
      <Head>
        <title>Solinvest | Dashboard</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <div className="flex ">
        <div className="w-[6%]  border-r border-[#2B2B2E]  ">
          <SideNav />
        </div>
        <div className="w-[94%] ">
          <Dashboard />
        </div>
      </div>
    </div>
  );
};

export default withAuthentication(dashboard);
