import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import SideNav from "../modules/SideNav/SideNav";
import { ShowBucketsContext } from "../hooks/ShowBucketsContext";
import { useState } from "react";
import { ActiveWindowContext } from "../hooks/ActiveWindowContext";
import UserProfile from "../modules/Profile/UserProfile";
import withAuthentication from "../hoc/ProtectedRoute";

const profile: NextPage = () => {
  const [showBuckets, setShowBuckets] = useState<boolean>(true);
  const [activeWindow, setActiveWindow] = useState("chat");
  return (
    <ShowBucketsContext.Provider value={{ showBuckets, setShowBuckets }}>
      <ActiveWindowContext.Provider value={{ activeWindow, setActiveWindow }}>
        <div className=" h-screen overflow-hidden  bg-[#141417] text-white antialiased">
          <Head>
            <title>Solinvest | Dashboard</title>
            {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
          </Head>
          <div className="flex h-full">
            <div className="w-[6%]  border-r border-[#2B2B2E] h-screen overflow-y-hidden  ">
              <SideNav />
            </div>
            <div className="w-[96%]  ">
              <UserProfile />
            </div>
          </div>
        </div>{" "}
      </ActiveWindowContext.Provider>
    </ShowBucketsContext.Provider>
  );
};

export default withAuthentication(profile);
