import React from "react";
import { useRouter } from "next/router";
import type { NextPage } from "next";
import Head from "next/head";
import withAuthentication from "../../hoc/ProtectedRoute";
import SideNav from "../../modules/SideNav/SideNav";
import TokensDashboard from "../../modules/Tokens/TokensDashboard";

const Tokens: NextPage = () => {
  const router = useRouter();
  const { token } = router.query;
  return (
    <div className=" h-full overflow-x-hidden bg-[#141417] text-white antialiased">
      <Head>
        <title>Solinvest | Dashboard</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <div className="flex h-full">
        <div className="w-[6%]  border-r border-[#2B2B2E]  ">
          <SideNav />
        </div>
        <div className="w-[94%] ">
          <TokensDashboard token={token} />
        </div>
      </div>
    </div>
  );
};

export default withAuthentication(Tokens);
